# permissions for end users to view mssqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mssql-viewer-role
rules:
- apiGroups:
  - microsoft.kubedb.com
  resources:
  - mssqls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - microsoft.kubedb.com
  resources:
  - mssqls/status
  verbs:
  - get
