apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysts
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        #fsGroup: 10001 # group ID of mssql
        runAsUser: 10001 # group ID of mssql
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          resources:
            requests:
              memory: "2G"
              cpu: "2000m"
            limits:
              memory: "2G"
              cpu: "2000m"
          ports:
            - containerPort: 1433
              name: mssql
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: MSSQL_SA_PASSWORD
          volumeMounts:
            - name: mssqldb
              mountPath: /var/opt/mssql
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: mypvc
            readOnly: true


# Important ENVs:
#- already added: ACCEPT_EULA, MSSQL_PID, SA_PASSWORD
#
#
#- name: MSSQL_DATA_DIR
#  value: /mssql-data/data
#- name: MSSQL_LOG_DIR
#  value: /mssql-translog/translog
#- name: MSSQL_BACKUP_DIR
#  value: /mssql-backup/backup
#- name: MSSQL_MASTER_DATA_FILE
#  value: /mssql-data/master/master.mdf
#- name: MSSQL_MASTER_LOG_FILE
#  value: /mssql-data/master/mastlog.ldf
#
#- name: MSSQL_TCP_PORT
#  value: "1433"
#- name: MSSQL_COLLATION
#  value: SQL_Latin1_General_CP1_CI_AS
#- name: MSSQL_LCID
#  value: "1033"
#- name: MSSQL_ENABLE_HADR
#  value: "0"
#- name: MSSQL_AGENT_ENABLED
#  value: "false"
#- name: MSSQL_MEMORY_LIMIT_MB
#  valueFrom:
#    resourceFieldRef:
#      divisor: 1Mi
#      resource: limits.memory
